sudo: required
services:
  - docker

#before_install:
#  - echo BEfore install
language: python
python:
  - "3.6"
  - pip3 install -r requirements.txt
notifications:
  slack: 
    rooms:
      - redklouds1:075OXfOwTatGBCewiUwzqylS
    on_success: always
    on_failure: always
  email:
    recipients:
      - dannyly199@gmail.com
  
  
jobs:
  include:
    - stage: test changes
      #before_script:
      #  - echo "this is before the test are run"

      script: 
        - python3 -m pytest -v
        - echo "FUCKING a"
      #after_script:
      #  - echo "do this after the scriupt is run"



