sudo: required
services:
  - docker
before_install:
  - echo BEfore install
notifications:
  slack: 
    rooms:
      - redklouds1:075OXfOwTatGBCewiUwzqylS
    
    on_success: always
    on_failure: always
  email:
    recipients:
      - dannyly199@gmail.com
    on_success: always
    on_failure: always

after_script:
  - echo "After script run here...."
  - echo "Another command "
  - echo ls -la
  - echo $HOME  
language: python
python:
  - "3.6"

  - pip3 install -r requirements.txt
script:
  - python3 -m pytest -v



after_script:
  jobs:
    include:
      - build docker image
      install:
        - docker build -t redklouds/$TRAVIS_REPO_SLUG .
        - docker run -d -rm --name test redklouds/$TRAVIS_REPO_SLUG
      script:
        - echo "Testing the build"
        - docker ps | grep -q test
      after_success:
        - echo "Success fully builed and tested docker file"

        - sh .travis/deploy_dockerhub.sh
after_success:
  - sh .travis/deploy_dockerhub.sh
