sudo: required
      #  - echo "do this after the scriupt is run"
services:
  - docker

#before_install:
#  - echo BEfore install
language: python
python:
  - "3.6"
  - pip3 install -r requirements.txt

notifications:
  slack: 
    rooms:
      - redklouds1:075OXfOwTatGBCewiUwzqylS
    on_success: always
    on_failure: always
  email:
    recipients:
      - dannyly199@gmail.com
  
 

script: 
  - python3 -m pytest -v
  - docker build -t test .
  - docker run -d --name test test
  - docker ps | grep -q test
after_success:
  - echo "after success"
  - sh .travis/deploy_dockerhub.sh
after_script:
  - echo "after script"
  - echo "Successfully tested docker build, pushing new image to repo now..."
